Repository ValentinH/react-easy-crop, pull requests merged in 2025-02, with the labels that each got.

#591 chore: update CI actions
  .github/workflows/quality-gate.yml
  .github/workflows/release.yml
Labels: dependencies, skip-release

#589 feat: emit crop data when a keyboard interaction is complete
  README.md
  src/Cropper.tsx
Labels: minor

#590 feat: add setCropperRef callback
  README.md
  src/Cropper.tsx
Labels: enhancement, minor

#593 feat: add cropperProps option to specify additional props for cropper
  README.md
  src/Cropper.tsx
Labels: patch
